[programs.devnet]
lpfinance_swap = "9jBjsXqKo6W54Hf65wrgR9k9AVYuCfDQQNUfygFtjWPJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/kk/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
